# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36687ef83040ba554dfe8321f454cd1b214b364cf8b3160f579c9e787c276cc32b7cda0faa5aab9a2d7e4747b8e30c5c5c91f6a7b3153360982dab62bfa4594d

test:
  secret_key_base: e1d3a103918cc2f4c469bf37de8fa59d91adbde7219e48b4a1936daad74070af8169d7deef3eb4dd912bb59e2265a299c13011303a76550c1dced5a2fc21f366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
